# Generated by Django 6.0.3 on 2026-03-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer faktury')),
                ('vendor_nip', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIP Sprzedawcy')),
                ('buyer_nip', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIP Nabywcy')),
                ('total_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kwota Brutto')),
                ('image_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ścieżka do pliku')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Czy przetworzono przez AI?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
        ),
    ]
